### ISSUE TITLE
Setup basic repo infra structure such as Travis / Bitbucket, etc

### ISSUE THREAD

**Issue by kienpham2000** [nnetworth/networth-meta#1]

**Comment by raoasifraza11** [comment]
For which language you want to stup a infra sturcuture as travis-ci? I can setup travis-ci for `python envirement` and `php`.

**Comment by kienpham2000** [comment]
@raoasifraza11 We use node.js for all of our repos. I've added you to collaborators for this repo with admin access, so you should be able to setup Travis. Thanks for your help!

**Comment by raoasifraza11** [comment]
Okay I'll setup Thank for adding me 👍

**Comment by raoasifraza11** [comment]
Added successfully #3 travis ci configuration.

**Comment by raoasifraza11** [comment]
@kienpham2000  Did we have a slack or anyother communication group?

**Comment by raoasifraza11** [comment]
@kienpham2000 Yeah, sure I'll add up travis configuration add me in repo's.

**Comment by kienpham2000** [comment]
cool will do. Let me close this ticket now it's done.
